### PR TITLE
Add support for costmap 3d

### PR DESCRIPTION
**Pull request by c-andy-martin**
Add the ability to use costmap 3d for costmaps in place of costmap 2d, based on a parameter.

Clearly, the costmap 3d code in navigation must be merged in first!

---
This change is [Reviewable](https://reviewable.io/reviews/badgertechnologies/move_base_flex/2)

### CODE REVIEW

**Review by howardcochran — CHANGES_REQUESTED** [review]
Possible typo in commit message for 7f55bbb:  "down-cast to the 3D costmap to make 3D queries":
s/3D/2D/g, I think.

> Reviewed 2 of 2 files at r1, 5 of 5 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/move_base_flex/2#-:-LyaA1wi8UXlHk4uakw0:b2ugcns)* status: all files reviewed, 2 unresolved discussions (waiting on @c-andy-martin)

___
*[mbf_costmap_nav/include/mbf_costmap_nav/costmap_3d_navigation_server.h, line 38 at r2](https://reviewable.io/reviews/badgertechnologies/move_base_flex/2#-LyaAcur9n6feD1uYmBi:-LyaAcur9n6feD1uYmBj:bcyqw7j) ([raw file](https://github.com/badgertechnologies/move_base_flex/blob/7f55bbbea99639adc7f96cc87663b32a94c8df9e/mbf_costmap_nav/include/mbf_costmap_nav/costmap_3d_navigation_server.h#L38)):*
> ```objc
>  *    Sebastian Pütz <spuetz@uni-osnabrueck.de>
>  *    Jorge Santos Simón <santos@magazino.eu>
>  *
> ```

Should you add yourself as author here?
___
*[mbf_costmap_nav/src/mbf_costmap_nav/costmap_3d_navigation_server.cpp, line 38 at r2](https://reviewable.io/reviews/badgertechnologies/move_base_flex/2#-LyaAqon7gRX9RO2SzPU:-LyaAqon7gRX9RO2SzPV:bouffqn) ([raw file](https://github.com/badgertechnologies/move_base_flex/blob/7f55bbbea99639adc7f96cc87663b32a94c8df9e/mbf_costmap_nav/src/mbf_costmap_nav/costmap_3d_navigation_server.cpp#L38)):*
> ```cpp
>  *    Sebastian Pütz <spuetz@uni-osnabrueck.de>
>  *    Jorge Santos Simón <santos@magazino.eu>
>  *
> ```

author?

**Comment by c-andy-martin** [comment]
___
*[mbf_costmap_nav/src/mbf_costmap_nav/costmap_3d_navigation_server.cpp, line 38 at r2](https://reviewable.io/reviews/badgertechnologies/move_base_flex/2#-LyaAqon7gRX9RO2SzPU:-LyesqCc9BBJXLax4Lxh:bjfzfzg) ([raw file](https://github.com/badgertechnologies/move_base_flex/blob/7f55bbbea99639adc7f96cc87663b32a94c8df9e/mbf_costmap_nav/src/mbf_costmap_nav/costmap_3d_navigation_server.cpp#L38)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

author?
</blockquote></details>

I'd rather leave this alone as I want to upstream eventually one day, and it seems better to leave all the copyrights the same for something so small. All I did was copy the 2d one and change a few things.

**Review by c-andy-martin — COMMENTED** [review]
The commit message is correct. The base-pointer is stored, a planner can attempt to down-cast to 3D. If it works, then they can make 3D queries.

> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/move_base_flex/2#-:-Lyes3BT63DYAB_0Blxc:bcwubsw)* status: all files reviewed, 2 unresolved discussions (waiting on @howardcochran)

___
*[mbf_costmap_nav/include/mbf_costmap_nav/costmap_3d_navigation_server.h, line 38 at r2](https://reviewable.io/reviews/badgertechnologies/move_base_flex/2#-LyaAcur9n6feD1uYmBi:-LyesafV5OJHOxoDC58N:b-vg8teq) ([raw file](https://github.com/badgertechnologies/move_base_flex/blob/7f55bbbea99639adc7f96cc87663b32a94c8df9e/mbf_costmap_nav/include/mbf_costmap_nav/costmap_3d_navigation_server.h#L38)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

Should you add yourself as author here?
</blockquote></details>

I'd rather leave this alone as I want to upstream eventually one day, and it seems better to leave all the copyrights the same for something so small. All I did was copy the 2d one and change a few things.

**Review by howardcochran — APPROVED** [review]
Oh, I see.  I had the wrong notion of "down"

> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/move_base_flex/2#-:-Lyj_IAy42p8ueVBd3JB:b-65bb2q)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
